Student: Kysylevych Yurii
Group: CE-47
Subject: CSDT

Project name: tic-tac-toe game 
Programming language: C

Additional tools/utils: Bash, Make
HW interface: SPI
Data driven format: JSON

Play modes: Man vs AI, Man vs Man, AI vs AI

AI supports next complexity levels: Random move, Win strategy

Actions: New, Save, Load

The proposal for data driven approach: configuration (saved in configuration file or DB): board size, distance, tool size, win statement, lose statement, AI parameters
